<a href="https://colab.research.google.com/github/Royal-tek/HMS/blob/master/Mr_Arowolo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

In [5]:
df = pd.read_csv(r'/content/bidmc_01_Signals.csv')

In [6]:
df.head(10)

Time [s]     RESP    PLETH        V      AVR       II
0     0.000  0.35386  0.43597  0.52549  0.30392  0.72549
1     0.008  0.35679  0.43206  0.51961  0.33529  0.67059
2     0.016  0.35875  0.42815  0.51569  0.37451  0.60980
3     0.024  0.36168  0.42424  0.50588  0.41961  0.55098
4     0.032  0.36364  0.42131  0.50980  0.44902  0.50000
5     0.040  0.36559  0.41838  0.50588  0.48039  0.45490
6     0.048  0.36657  0.41740  0.51569  0.50980  0.40980
7     0.056  0.36852  0.41642  0.51569  0.51961  0.39020
8     0.064  0.36852  0.41544  0.51961  0.53529  0.37451
9     0.072  0.36852  0.41447  0.51961  0.54510  0.35882

In [7]:
df.shape

(60001, 6)

In [8]:
df.isnull().sum()

Time [s]    0
 RESP       0
 PLETH      0
 V          0
 AVR        0
 II         0
dtype: int64

In [81]:
X = df.drop(columns=' AVR', axis=1).values
Y = df[' AVR'].values

In [82]:
print(X.shape)
print(Y.shape)



(60001, 5)
(60001,)


In [83]:
print(X)
print(Y)


[[0.0000e+00 3.5386e-01 4.3597e-01 5.2549e-01 7.2549e-01]
 [8.0000e-03 3.5679e-01 4.3206e-01 5.1961e-01 6.7059e-01]
 [1.6000e-02 3.5875e-01 4.2815e-01 5.1569e-01 6.0980e-01]
 ...
 [4.7998e+02 1.4663e-01 4.0176e-01 5.0000e-01 3.8431e-01]
 [4.7999e+02 1.4174e-01 4.0176e-01 5.0000e-01 3.8039e-01]
 [4.8000e+02 1.3783e-01 4.0274e-01 4.9412e-01 3.8039e-01]]
[0.30392 0.33529 0.37451 ... 0.53529 0.53922 0.53529]


In [84]:
X_train, Y_train, X_test, Y_test = train_test_split(X, Y, random_state=2, test_size=0.2)


In [85]:
sc = StandardScaler()
preX = sc.fit_transform(Y_train)
preY = sc.fit_transform(X_train)


In [86]:

print(preX)

[[-1.12551534 -0.31518041 -0.51653366 -0.0255931   1.25019853]
 [-1.03439773 -0.28178916  1.33694935  0.22227209 -0.22262265]
 [-0.95312129 -0.46683754 -0.21758479  0.03339376 -0.50716577]
 ...
 [-1.30607178 -0.6397521  -0.74070709  0.24586683 -0.52389607]
 [ 1.73192482 -0.65796833  1.75547777 -0.0255931   0.89036906]
 [-1.33941596  1.2956373  -0.68091732  0.55271888 -0.50716577]]


In [87]:
preX = preX.flatten()

In [88]:
print(preX.shape)
print(preY.shape)

(60005,)
(48000, 5)


In [89]:
from sklearn.svm import SVC

In [90]:
model = SVC()